### ISSUE TITLE
nodefs Connector frequently rejects BATCH_FORGET

### ISSUE THREAD

**Issue by divVerent** [hanwen/go-fuse#126]
Filing this mainly to document this - I observed that nodefs's Connector frequently rejects BATCH_FORGET requests.

One way to reproduce this:
- Apply the patch from the attached extradebug.diff.txt (which logs these events when Debug is set).
- Extract testdir.tar.gz somewhere.
- Build examples/loopback.
- Run:

```
$ ./loopback -debug /tmp/mnt /path/to/extracted/testdir/tmp/v
```

and on another shell:

```
$ du /tmp/mnt
$ fusermount -u /tmp/mnt
```

Observe log messages like in extradebug.log.txt (attached):

```
16:03:58.915280 Dispatch 784: BATCH_FORGET, NodeId: 0. data: {Count=7}  112 bytes
16:03:58.915300 doBatchForget: forgetting 1 of 7: NodeId: 105, Nlookup: 1
16:03:58.915318 Dispatch 782: BATCH_FORGET, NodeId: 0. data: {Count=2}  32 bytes
16:03:58.915331 doBatchForget: forgetting 1 of 2: NodeId: 112, Nlookup: 1
16:03:58.915285 Dispatch 783: BATCH_FORGET, NodeId: 0. data: {Count=5}  80 bytes
16:03:58.915434 doBatchForget: forgetting 1 of 5: NodeId: 110, Nlookup: 1
[...]
16:03:58.915516 doBatchForget: forgetting 4 of 7: NodeId: 12, Nlookup: 1
16:03:58.915528 forgetUpdate for nodeID 12 (paths: [/7])
16:03:58.915601 forgetUpdate for nodeID 12 which has children map[9:0xc420101dc0 5:0xc420101e30 0:0xc420101d50 7:0xc42001e0e0 8:0xc420101ea0 4:0xc420101f10 2:0xc420101f80]
[...]
16:03:58.915785 doBatchForget: forgetting 4 of 5: NodeId: 107, Nlookup: 1
16:03:58.915792 forgetUpdate for nodeID 107 (paths: [/7/9])
```

Analysis attempt:
- The count=7 batch gets processed first, which wants to forget /7. However, /7/9 still exists.
- The count=5 batch is actually the one which would forget /7/9. Too bad it gets processed last.
- The request indexes in Dispatch: seem to be in the correct order, though.
- This happens despite me setting SingleThreaded: true.

Fix ideas:
- Try processing BATCH_FORGET always in the order of requests.
- Maybe better: call Forget(h, 0) and the other stuff on a parent once it no longer has any children (as part of rmChild). That'll remove the reliance on topological ordering of the input, at some runtime cost.

Files to reproduce this:

[extradebug.diff.txt](https://github.com/hanwen/go-fuse/files/473393/extradebug.diff.txt)
[testdir.tar.gz](https://github.com/hanwen/go-fuse/files/473395/testdir.tar.gz)

[extradebug.log.txt](https://github.com/hanwen/go-fuse/files/473394/extradebug.log.txt)

**Comment by hanwen** [comment]
@rfjakob has been looking into forget a lot lately.

**Comment by hanwen** [comment]
https://github.com/hanwen/go-fuse/blob/master/fuse/nodefs/fsconnector.go#L143 

the ordering is not guaranteed. That would also be tricky, since FORGET has no return value, so you can't define an ordering on the different FORGET or BATCH`FORGET calls.

what we should do (I think) is to have FORGET on a directory node detach all its children nodes, which would then become forgotten on their own.

However, your original question (which didn't make it into the bugreport) involved attaching semantics to FORGET messages. This is a bad idea: the kernel is under no obligation to ever issue FORGET messages, and if your dependent action can fail, there is no place to report the failure.

**Comment by hanwen** [comment]
This is fixed in the v2 fs API, which can destroy the tree even if FORGET requests arrive out of order.
