### ISSUE TITLE
Usage of file Open in nodefs

### ISSUE THREAD

**Issue by itaysk** [hanwen/go-fuse#186]
Sorry to post a usage question here, but I couldn't find anywhere else (tried StackOverflow, no takers).

I created a nodefs filesystem, and everything works except files are not opened.
Basically the file node is similar to:

```
type SomeFileNode struct {
    nodefs.Node
    content string
}

func (this *SomeFileNode) Open(flags uint32, context *fuse.Context) (nodefs.File, fuse.Status) {
    return nodefs.NewDataFile([]byte(this.content)), fuse.OK
}
```

I expect to `cat` that file, but nothing is printed to stdout.
What am I missing?

Full repro here: https://pastebin.com/MmTZQ7Ah

**Comment by hanwen** [comment]
Implement getattr returning nonzero size

Op 15 sep. 2017 07:44 schreef "Itay Shakury" <notifications@github.com>:

Sorry to post a usage question here, but I couldn't find anywhere else
(tried StackOverflow, no takers).

I created a nodefs filesystem, and everything works except files are not
opened.
Basically the file node is similar to:

type SomeFileNode struct {
    nodefs.Node
    content string
}

func (this *SomeFileNode) Open(flags uint32, context *fuse.Context)
(nodefs.File, fuse.Status) {
    return nodefs.NewDataFile([]byte(this.content)), fuse.OK
}

I expect to cat that file, but nothing is printed to stdout.
What am I missing?

Full repro here: https://pastebin.com/MmTZQ7Ah

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hanwen/go-fuse/issues/186>, or mute the thread

**Comment by itaysk** [comment]
Thanks for the quick response! That fixed the problem.
If I may, a followup question: 
I wanted to avoid actually getting the file's content until `Open` (in order to minimize network calls), but GetAttr is called more often (`ls -l`).
Is there a better way to implement this?
- Returning arbitrary non-zero size will not work (causes trim or error)
- Will implementing `Read` instead of `Open` help me here?

**Comment by hanwen** [comment]
you might want to try opening the file for DIRECT_IO and without KEEP_CACHE.

**Comment by itaysk** [comment]
Thanks for the reply, not sure what it means at this point but I'll do my research on this. Closing this issue, Thanks again.

**Comment by jim-minter** [comment]
@itaysk in your `func (*fs) Open()`, instead of, say,

```
return nodefs.NewDataFile([]byte("hello")), fuse.OK
```

try

```
return &nodefs.WithFlags{
	File:      nodefs.NewDataFile([]byte("hello")),
	FuseFlags: fuse.FOPEN_DIRECT_IO,
}, fuse.OK
```

See https://github.com/hanwen/go-fuse/commit/ceac407356281c09941720665e1e17dde59f91e8.
