### ISSUE TITLE
What is the use of File.SetInode()?

### ISSUE THREAD

**Issue by EdSchouten** [hanwen/go-fuse#256]
nodefs.Node has two functions: SetInode() and Inode(). These are used by go-fuse to attach data to a Node object, presumably so it can always get access to its own bookkeeping if it only gets a reference to a Node.

File also seems to have a SetInode() function, but no corresponding Inode(). My question is, what's the purpose of this call? File objects are created through Node.Open() and Node.Create(). Both functions already have access to the Inode object prior to returning, meaning there would be no need for go-fuse to hand that information back through File.SetInode(), right?

**Comment by hanwen** [comment]
it's currently used in unionfs.go:1022  ; maybe you're right, and this should be handled from open/create. PR appreciated.

**Comment by hanwen** [comment]
I looked a bit more at this. The problem is that PathFS takes over inode to offer a path based API. If you're in the Create(string path) method, you don't have the inode to store in the File. 

Maybe this should have been handled by having the PathFS return a separate PathFile struct, but it is too late for that now.

i'll a documentary note.
