### ISSUE TITLE
Override/Enhance Loopback FS functionality

### ISSUE THREAD

**Issue by donovan-duplessis** [hanwen/go-fuse#364]
Hi there,

Is it possible to override the loopbackRoot FS implementation?  We would like to enhance some methods (read, write etc) to suit our needs.  We specifically want to create a loopback filesystem with enhanced file access permissions, i.e. the ability to block certain files from being read.

If this is possible, could you point me in the right direction to implement, with say a very basic example?

Regards,
Donovan

**Comment by EdoaLive** [comment]
Same problem here: I was going to "enhance" the loopbackfs (actually I'm writing a custom unionfs) that wraps or embed most of the loopback functions, but I immediately realized that I can't do that because there are too many unexported symbols.

I think that most examples just work because they directly use "API" calls, but as soon as you try to customize or change something, you realize that actual examples are inside the fs package, and you can't directly use most of it in the current state. Moreover, some examples (the most complex ones) are based on the "deprecated" (v1?) API.

My current workaround will be to fork this repo and directly work inside the fs package, but I strongly suggest the authors to review the API codebase towards a more customizable and easily exploitable way.

**Comment by hanwen** [comment]
The return value of NewLoopbackRoot is an InodeEmbedder.

Doesnt it work to embed that into another struct ? You have to override Lookup and Create as well to return your own flavor of InodeEmbedder too.

**Comment by EdoaLive** [comment]
Maybe I'm too new at Go but I can't see how to do that, or I didn't find the right example. 
Let's say I need a filesystem that is exactly like loopback, except Getattr() always set a specific bit in syscall.Stat_t.Mode. How would I do that?
(I took Getattr just to make a simple example, in the real world I think I should work on the path() method of loopbackNode, which is private btw)
I wonder if this is doable without rewriting the whole Getattr(), if not, it pretty much means that in my final project I'm going to rewrite the whole loopback.go anyway just to change some lines.

**Comment by hanwen** [comment]
getattr is easy, 

```
type myNode struct {
  InodeEmbedder
}
func (n* myNode) Getattr(..., attr *fuse.Attr) {
   errno := n.InodeEmbedder.Getattr(..)
   attr.Mode |= 0x135
   return errno
}
```

the problem comes with injecting the `myNode` instance in the place where you need it (ie. in Create and Lookup).  

Note that you can get the path relative to the root from Inode.Path().

The previous version of the api `fuse/pathfs` had facilities for reuse, but it actually complicated more advanced use cases. What would be the right API for injecting the &myNode{} instance in Lookup/Create ? Should it be allowed to nodes that are not loopback nodes as children of loopback nodes?

**Comment by hanwen** [comment]
> and you can't directly use most of it in the current state.

which examples specifically?

**Comment by EdoaLive** [comment]
I'm sorry, I still don't get how to obtain a myNode instance that "mixes" with the InodeEmbedder obtained with NewLoopbackRoot().
I'm trying something like this but it doesn't loopback anything:
```
type myNode struct {
  InodeEmbedder
}

func (n* myNode) Getattr(...

func NewMyRoot(root string) (InodeEmbedder, error) {
	l, err := fuse_fs.NewLoopbackRoot(root)
	if err != nil {
		return nil, err
	}

	n := &myNode{ l }

	return n, nil
}
```
What is the correct way?

**Comment by EdoaLive** [comment]
Also
> getattr is easy,

It's not so easy: `r.InodeEmbedder.Getattr undefined (type fs.InodeEmbedder has no field or method Getattr)`

Full code example: https://play.golang.org/p/ZzWMO3dZDIT

What am I doing (or thinking) wrong?

**Comment by hanwen** [comment]
oh, `r.InodeEmbedder.Ops().Getattr` (or similar) I guess.

**Comment by EdoaLive** [comment]
> oh, `r.InodeEmbedder.Ops().Getattr` (or similar) I guess.

I tried also similar but couldn't find anything like this.
>Let's say I need a filesystem that is exactly like loopback, except Getattr() always set a specific bit in syscall.Stat_t.Mode. How would I do that?

Could you please show me a complete (working) example (should be a few more lines than your post above)?
I think I know how to go from there.
Thanks

**Comment by hanwen** [comment]
I added a prototype of what this could look like, see https://review.gerrithub.io/c/hanwen/go-fuse/+/508223/1/fs/windows_example_test.go

I would welcome some feedback, especially what parameters you need in the signature of NewChild.
