### ISSUE TITLE
Stance on BSD support

### ISSUE THREAD

**Issue by cetinsert** [hanwen/go-fuse#366]
```shell
$ go build
go: downloading golang.org/x/net v0.0.0-20200520182314-0ba52f642ac2
go: downloading github.com/hanwen/go-fuse v1.0.0
go: downloading github.com/araddon/dateparse v0.0.0-20200409225146-d820a6159ab1
go: downloading github.com/hanwen/go-fuse/v2 v2.0.3
go: downloading golang.org/x/sys v0.0.0-20200523222454-059865788121
# github.com/hanwen/go-fuse/v2/fuse
../go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.0.3/fuse/api.go:218:41: undefined: GetAttrIn
../go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.0.3/fuse/api.go:219:41: undefined: SetAttrIn
../go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.0.3/fuse/api.go:222:39: undefined: MknodIn
../go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.0.3/fuse/api.go:246:42: undefined: SetXAttrIn
../go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.0.3/fuse/api.go:252:40: undefined: CreateIn
../go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.0.3/fuse/api.go:254:38: undefined: ReadIn
../go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.0.3/fuse/api.go:263:39: undefined: WriteIn
../go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.0.3/fuse/api.go:272:41: undefined: ReadIn
../go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.0.3/fuse/types.go:550:2: undefined: Attr
../go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.0.3/fuse/types.go:578:2: undefined: Attr
../go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.0.3/fuse/api.go:272:41: too many errors
$ uname -a
FreeBSD freebsd 12.1-RELEASE-p5 FreeBSD 12.1-RELEASE-p5 GENERIC  amd64
```

a project I am working on does not build on `FreeBSD`.

1. Why does this project not support *BSDs?
2. Can you compare this project to https://github.com/bazil/fuse (which works on FreeBSD) in terms of 
    1. performance
    2. how well the two are maintained
    3. reliability/stability
    4. features?

**Comment by rfjakob** [comment]
I guess if you write types_freebsd.go (compare https://github.com/hanwen/go-fuse/blob/master/fuse/types_darwin.go) there should not be a lot keeping it from working.

**Comment by cetinsert** [comment]
@rfjakob actually one needs all of the below

```
   attr_freebsd.go
  mount_freebsd.go
   poll_freebsd.go
request_freebsd.go
 server_freebsd.go
 splice_freebsd.go
  types_freebsd.go
```

**Comment by hanwen** [comment]
Unfortunately, I don't have the time to install and tinker with fuse on FreeBSD, but I am happy to accept changes that add support.


Some points to consider: 

* bazil. maintenance effort seems bursty; it lingered for a year or so, but things are happening now.
* I prefer my own v2/fs/ API ;-)
* @rfjakob has been testing go-fuse file systems with fsstress, so the library is very solid.
* last time I looked, go-fuse performance on Linux was better, both due to more aggressive memory reuse, and better API support (readdirplus). This may have changed, though.
* bazil.org supports the POLL opcode, at the expense of considerable extra complexity for unit tests.
See https://github.com/hanwen/go-fuse/issues/165, https://github.com/bazil/fuse/issues/183 and https://github.com/bazil/fuse/commit/3f5ad9058d81bedd9d0181e676373e6b8053bb2a)

**Comment by hanwen** [comment]
I'm closing this, as I've documented my stance on BSD support in the previoius comment.
