### ISSUE TITLE
Interrupt called after OK response

### ISSUE THREAD

**Issue by glp-p4** [hanwen/go-fuse#375]
On Linux with the current version of go-fuse v2, I have been seeing this happen a fair bit lately. I am not sure if this is a bug or something I am doing wrong on my end. But basically, it looks like the client is receiving interrupt requests after the operation has already returned successfully. Any idea what might be going on?
```
rx 700: FLUSH i76102 {Fh 2} 
tx 700:     OK
rx 701: INTERRUPT i0 {ix 700} 
tx 701:     11=resource temporarily unavailable
writer: Write/Writev failed, err: 2=no such file or directory. opcode: INTERRUPT
```

**Comment by glp-p4** [comment]
Clarification, I meant the most recent release tag (v2.0.3), not the current master.

**Comment by glp-p4** [comment]
For a bit more context, I have been trying to benchmark roughly how long certain operations, such as file creation, are taking in my filesystem. For file creation, I have a little utility such as the one below (called "create.go"), and I run ./create 10000 to rapidly create 10000 files sequentially. This causes the above error to occasionally crop up. Other than littering the log with some error messages, everything still appears to work, but obviously I want to make sure that there is not a fire somewhere.
```
package main

import (
	"fmt"
	"log"
	"os"
	"strconv"
	"time"
)

func main() {
	log.SetFlags(0)
	n, err := strconv.Atoi(os.Args[1])
	if err != nil {
		log.Panicln(err)
	}
	log.Printf("Creating %d file(s)...\n", n)
	start := time.Now()
	for i := 0; i < n; i++ {
		fname := fmt.Sprintf("file_%09d", i)
		f, err := os.Create(fname)
		if err != nil {
			log.Panicln(err)
		}
		f.Close()
	}
	elapsed := time.Now().Sub(start).Seconds()
	each := float64(elapsed) / float64(n)
	log.Printf("Elapsed: %fs, Each: %fs\n", elapsed, each)
}
```

**Comment by glp-p4** [comment]
Hi guys, so any idea what could be going on here? This behavior is causing havoc with my project and I have no idea where it is coming from. These spurious interruptions (some of which appear to be issued after successful completion of ops) are causing all kinds of issues. For example (see below), a file create request is issued and then interrupted and then re-issued, creating a conflict because the first create actually already had succeeded.

```
rx 2118: GETATTR i1 {Fh 0} 
tx 2118:     OK, {tA=1s {M040755 SZ=0 L=2 1000:1000 B0*4194304 i0:1 A 1601535056.532883 M 1601535084.844758 C 1601535084.844758}}
rx 2122: LOOKUP i1 ["file_000000168"] 15b
tx 2122:     2=no such file or directory, {i0 g0 tE=0s tA=0s {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000}}
rx 2124: CREATE i1 {0100664 [RDWR,CREAT,TRUNC,0x8000] (02)} ["file_000000168"] 15b
tx 0:     NOTIFY_INVAL_ENTRY, {parent i1 sz 14} "file_000000168"
tx 2124:     OK, {i171 g0 {M0100664 SZ=0 L=1 1000:1000 B0*4194304 i0:171 A 1601535084.846585 M 1601535084.846585 C 1601535084.846585} &{2 0 0}}
Response: ENTRY_NOTIFY: OK
rx 2126: FLUSH i171 {Fh 2} 
tx 2126:     OK
rx 2128: RELEASE i171 {Fh 2 NONBLOCK,RDWR,0x8000  L0} 
tx 2128:     OK
rx 2130: GETATTR i1 {Fh 0} 
rx 2132: FORGET i171 {Nlookup=1} 
tx 2130:     OK, {tA=1s {M040755 SZ=0 L=2 1000:1000 B0*4194304 i0:1 A 1601535056.532883 M 1601535084.846585 C 1601535084.846585}}
rx 2134: LOOKUP i1 ["file_000000169"] 15b
tx 2134:     2=no such file or directory, {i0 g0 tE=0s tA=0s {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000}}
rx 2136: CREATE i1 {0100664 [CREAT,TRUNC,RDWR,0x8000] (02)} ["file_000000169"] 15b
tx 0:     NOTIFY_INVAL_ENTRY, {parent i1 sz 14} "file_000000169"
tx 2136:     OK, {i172 g0 {M0100664 SZ=0 L=1 1000:1000 B0*4194304 i0:172 A 1601535084.848270 M 1601535084.848270 C 1601535084.848270} &{2 0 0}}
Response: ENTRY_NOTIFY: OK
rx 2138: FLUSH i172 {Fh 2} 
tx 2138:     OK
rx 2140: RELEASE i172 {Fh 2 NONBLOCK,RDWR,0x8000  L0} 
tx 2140:     OK
rx 2144: FORGET i172 {Nlookup=1} 
rx 2143: INTERRUPT i0 {ix 2142}
rx 2142: GETATTR i1 {Fh 0} 
tx 2142:     OK, {tA=1s {M040755 SZ=0 L=2 1000:1000 B0*4194304 i0:1 A 1601535056.532883 M 1601535084.848270 C 1601535084.848270}}
rx 2146: LOOKUP i1 ["file_000000170"] 15b
tx 2146:     2=no such file or directory, {i0 g0 tE=0s tA=0s {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000}}
rx 2147: INTERRUPT i0 {ix 2146} 
rx 2148: CREATE i1 {0100664 [RDWR,TRUNC,CREAT,0x8000] (02)} ["file_000000170"] 15b
tx 2147:     11=resource temporarily unavailable
writer: Write/Writev failed, err: 2=no such file or directory. opcode: INTERRUPT
rx 2149: INTERRUPT i0 {ix 2148} 
tx 2148:     4=interrupted system call, {i0 g0 {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000} &{0 0 0}}
rx 2150: LOOKUP i1 ["file_000000170"] 15b
tx 2150:     2=no such file or directory, {i0 g0 tE=0s tA=0s {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000}}
rx 2152: CREATE i1 {0100664 [RDWR,CREAT,TRUNC,0x8000] (02)} ["file_000000170"] 15b
Error (Create): response.Status: ErrInternal
tx 2152:     5=input/output error, {i0 g0 {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000} &{0 0 0}}
rx 2154: RELEASE i2 {Fh 1 0x8020  L0} 
tx 2154:     OK
```

**Comment by hanwen** [comment]
```
writer: Write/Writev failed, err: 2=no such file or directory. opcode: INTERRUPT
```

this looks impossible:  see

https://github.com/hanwen/go-fuse/blob/0b6cbc5150825082d3edd3c4be05e9d3991792a0/fuse/server.go#L513

_OP_INTERRUPT always returns OK, and the log statement never triggers if status == OK.

https://github.com/hanwen/go-fuse/blob/0b6cbc5150825082d3edd3c4be05e9d3991792a0/fuse/server.go#L477

Is this code clean when you run with -race?

>  the first create actually already had succeeded.

then why does it return EINTR if it succeeded? The proper error code is OK, then. Which filesystem code are you using?

**Comment by glp-p4** [comment]
I tried using -race, but it didn't kick up any warnings. You have a point about returning EINTR. I have requests in flight to a remote server and it isn't too easy to completely cancel them as there are all kinds of timing issues there. I just disabled all interrupt handling (by ignoring the cancel channel altogether) and the re-issuance problem goes away as expected. That said, I still don't get where the interrupts are coming from and why there are so many. I am using the raw filesystem from v2.0.3 (using go modules).

Here is a code snippet from my Create implementation:
```
// Create implementation.
func (o *MyFS) Create(cancel <-chan struct{}, in *fuse.CreateIn, name string, out *fuse.CreateOut) fuse.Status {
	if len(name) > 255 {
		return fuse.Status(syscall.ENAMETOOLONG)
	}
	if in.NodeId > setting.MaxRegularIno {
		return fuse.ENOTSUP
	}
	requestPayload := payload.NewMkNodRequest(in.NodeId, in.Uid, in.Gid, in.Mode, name)
	request := protocol.NewMkNodRequest(requestPayload)
	select {
	/*
		case <-cancel:
			api.Cancel(request.ID)
			return fuse.EINTR
	*/
	case response, ok := <-api.Send(request):
		if ok {
			if response.Status == status.Ok {
				if responsePayload, ok := response.Payload.(*payload.MkNodResponse); ok {
					attr := responsePayload.ChildAttr
					o.prepareEntry(attr, &out.EntryOut)
					fh, _, err := o.openFh(attr.Ino, attr.Size, in.Flags, attr.Mode)
					if err != nil {
						log.Println("Error (Create.openFh):", err)
						return fuse.EIO
					}
					out.Fh = fh
					return fuse.OK
				}
				log.Println("Error (Create): Invalid response payload")
				return fuse.EIO
			} else if response.Status == status.ErrAuth {
				o.ErrAuth <- struct{}{}
				return fuse.EACCES
			}
			log.Println("Error (Create): response.Status:", response.Status)
		} else {
			log.Println("Error (Create): Response channel closed before response arrived")
		}
	}
	return fuse.EIO
}
```

I have also included a full output log (attached below) of me simply creating 100 files in a completely clean mountpoint using the -race flag as well. For some unknown reason, it has several instances of:
```
writer: Write/Writev failed, err: 2=no such file or directory. opcode: INTERRUPT
```
[output.log](https://github.com/hanwen/go-fuse/files/5312398/output.log)

**Comment by schwittmann** [comment]
I experienced similar errors with v2.0.3 after upgrading from go 1.13 to 1.14; suddenly unittests failed which were previously running just fine. Can you, @glp-p4, confirm that you were also using a go version >= 1.14?

The issue seems to be related to asynchronously preemptible goroutines introduced in that [version](https://golang.org/doc/go1.14#runtime): The increased amount of SIGURG used to preempt routines causes INTERRUPT messages to be generated much more frequently.

To isolate the behavior I [extended](https://github.com/schwittmann/go-fuse-interrupt/blob/master/main.go) the hello world example and ran it using both go [1.13.8](https://raw.githubusercontent.com/schwittmann/go-fuse-interrupt/master/output_go_1.13.8_linux_amd64.txt) and [1.14.7](https://raw.githubusercontent.com/schwittmann/go-fuse-interrupt/master/output_go_1.14.7_linux_amd64_debug_10.txt). Note that the error "Write/Writev failed, err: 2=no such file or directory. opcode: INTERRUPT" only appeared with 1.14.7.

I was initially confused how a write() systemcall could return an ENOENT/"no such file or directory" error code as this is neither mentioned in posix nor in linux documentation. Finally a close look at the linux [fuse driver](https://github.com/torvalds/linux/blob/master/fs/fuse/dev.c#L1872) for /dev/fuse reveals that ENOENT is used to indicate that a fuse request referred to in a fuse response is no longer known to the kernel.

This is exactly what happened in the log posted [above](https://github.com/hanwen/go-fuse/issues/375#issuecomment-701932706):
```
rx 2146: LOOKUP i1 ["file_000000170"] 15b
tx 2146:     2=no such file or directory, {i0 g0 tE=0s tA=0s {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000}}
rx 2147: INTERRUPT i0 {ix 2146}
rx 2148: CREATE i1 {0100664 [RDWR,TRUNC,CREAT,0x8000] (02)} ["file_000000170"] 15b
tx 2147:     11=resource temporarily unavailable
writer: Write/Writev failed, err: 2=no such file or directory. opcode: INTERRUPT
```
Request 2146 is received and answered. The kernel removes this completed request from memory. Afterwards, due to non-deterministic behavior on the channel, request 2147 is received which asks 2146 to be interrupted. In go-fuse a [lookup](https://github.com/hanwen/go-fuse/blob/be8e5f4a85fd132e835e9dd9f34ecebce48e7462/fuse/opcode.go#L489) is performed whether the referred request is currently in-flight. As 2146 is already completed, EAGAIN is written in a response (11=resource temporarily unavailable). The kernel reads the interrupt response to a nonexisting request and returns ENOENT - which is printed by go-fuse.


**Solution**

Fundamentally, the log message "Write/Writev failed" causes no harm. Like @glp-p4, my failed unittests had their origin in canceled fs calls which have no proper rollback mechanisms. So **TL/DR**: if you cannot safely rollback fs operations don't return EINTR in your fs implementations. If you do have rollback mechanisms don't forget to return EINTR.

To prevent this log entry and unnecessary interrupt responses go-fuse could handle INTERRUPT requests more gracefully: If a response has already been written (as seen above) an additional interrupt response is not necessary (cf. [fuse documentation](https://github.com/torvalds/linux/blob/bbe85027ce8019c73ab99ad1c2603e2dcd1afa49/Documentation/filesystems/fuse.rst#interrupting-filesystem-operations), even completely ignoring them is fine).

On the other hand, if the interrupt refers to a previous unseen request, that request should be canceled as soon as it reaches go-fuse and not be handed over to fs implementations. Currently, the code takes the fuse recommendation ("If the filesystem cannot find the original request, it should wait for some timeout and/or a number of new requests to arrive, after which it should reply to the INTERRUPT request with an EAGAIN error.") literary: if the request cannot be found EAGAIN is returned after a [sleep](https://github.com/hanwen/go-fuse/blob/be8e5f4a85fd132e835e9dd9f34ecebce48e7462/fuse/opcode.go#L489) - no matter what. I assume the authors intended one should also check for that interrupted request during that time. Maybe track these ids in a separate list/map?

**Comment by glp-p4** [comment]
@schwittmann I can confirm that I am using a version 1.15.6 of Go (> 1.14).

**Comment by tomyl** [comment]
Since the warning messages for `INTERRUPT` seem harmless, how about just suppressing them unless debug output is enabled? Something like:
```diff
--- a/fuse/server.go
+++ b/fuse/server.go
@@ -485,8 +485,10 @@ func (ms *Server) handleRequest(req *request) Status {
 
        errNo := ms.write(req)
        if errNo != 0 {
-               log.Printf("writer: Write/Writev failed, err: %v. opcode: %v",
-                       errNo, operationName(req.inHeader.Opcode))
+               if ms.opts.Debug || req.inHeader.Opcode != _OP_INTERRUPT {
+                       log.Printf("writer: Write/Writev failed, err: %v. opcode: %v",
+                               errNo, operationName(req.inHeader.Opcode))
+               }
        }
        ms.returnRequest(req)
        return Status(errNo)
```

**Comment by rfjakob** [comment]
Makes sense to me, care to push this as a PR? @hanwen looks small enough to not need Gerrit, what do you think?

**Comment by hanwen** [comment]
Please use Gerrit. I don´t think the syncing is bidirectional.

**Comment by tomyl** [comment]
Pushed https://review.gerrithub.io/c/hanwen/go-fuse/+/518519

Thank you @schwittmann for your analysis btw!
