### ISSUE TITLE
go-fuse currently not support macfuse 4.0.0

### ISSUE THREAD

**Issue by chnliyong** [hanwen/go-fuse#379]
[osxfuse](https://osxfuse.github.io/) changed its name to macfuse since version [4.0.0](https://github.com/osxfuse/osxfuse/releases/tag/macfuse-4.0.0) released. Below paragraph is copied from [changelog](https://github.com/osxfuse/osxfuse/releases/tag/macfuse-4.0.0):
- Drop support for deprecated "old style" mount process. Opening a /dev/macfuse device and passing the file descriptor to mount_macfuse is no longer supported ("old style"). mount_macfuse passes the file descriptor to the calling library over a socket ("new style", introduced in version 3.3.0).

In [changlog](https://github.com/osxfuse/osxfuse/releases/tag/osxfuse-3.3.0) of version 3.3.0, it states this:
- Implement new style mount process

  When mounting a FUSE volume on Linux, fusermount opens the FUSE device and passes the file descriptor back to libfuse.

  However, on OS X libosxfuse used to be responsible for locating a free FUSE device, opening it, and then passing the file descriptor to mount_osxfuse. For this to work libosxfuse needs to be aware of low level implementation details like the number of registered FUSE devices.

  In order to decouple libosxfuse from the FUSE kernel extension the mount process has been revised to match FUSE on Linux. mount_osxfuse will locate a free FUSE device, open it, and then pass the file descriptor back to libosxfuse.

go-fuse currently seems to depend on this "old style".

**Comment by hanwen** [comment]
yes, you are probably right. I don't own an OSX machine, so support for OSXFUSE (or MacFUSE) is a bit a spotty. 

I would welcome well tested changes to support FUSE on newer versions of OSX.

**Comment by llucps** [comment]
I own a macOS machine and I use gocryptfs with OS X Fuse 3.2, so I'm really interested to make the new macFUSE 4 compatible with go-fuse.

How can I help? I'm not a developer but happy to test anything on my machine.

Thanks.

**Comment by hanwen** [comment]
Thanks for the offer. Let me see if I can find some example code of how to do the new style mounting on OSX.

**Comment by hanwen** [comment]
do you know of example code that exercises this new style mounting on OSX ?

the other fuse library has simply removed OSX wholesale, https://github.com/bazil/fuse/commit/60eaf8f021ce00e5c52529cdcba1067e13c1c2c2 - it is fairly drastic, but the reasoning is sound. Apple has discontinued the mechanism that lets you build extensions to the kernel.

**Comment by llucps** [comment]
Unfortunately I don't.. it seems macFuse source code is net being released anymore...

Someone asked how the new moint protocol works on version 4:

https://github.com/osxfuse/osxfuse/issues/742

I'm afraid that unless something changes.. will be difficult to get go-fuse to work with macFuse 4... :(

**Comment by midchildan** [comment]
The userspace library for macFUSE, libfuse, is actually open source because it's forked off GPL'ed code. I did some digging, and here's what I found.

##### Relevant Commits

###### The "New Style" Mount
https://github.com/osxfuse/fuse/commit/8afa4eabdddb7fc9e810f43666462c4d2451925f

###### Rebranding
This contains path changes and renaming of environment variables.
https://github.com/osxfuse/fuse/commit/0eda6da8fb6f786e1126ef4ff5d869036d5ba760
https://github.com/osxfuse/fuse/commit/a62ee637c2ee70b08473ff69f7af66356658cde3

##### Interesting Parts of the Code Regarding the "New Style" Mount Process

Create a new socket pair
https://github.com/osxfuse/fuse/blob/c6a59bed40bb526c113f861ed49a78b5f224805a/lib/mount_darwin.c#L434

Pass one end of the socket to the mount program via the `_FUSE_COMMFD` environment variable
https://github.com/osxfuse/fuse/blob/master/lib/mount_darwin.c#L473-L475

Run the mount program:
https://github.com/osxfuse/fuse/blob/c6a59bed40bb526c113f861ed49a78b5f224805a/lib/mount_darwin.c#L488

Wait for the mount program to send the fuse device fds via the socket:
https://github.com/osxfuse/fuse/blob/c6a59bed40bb526c113f861ed49a78b5f224805a/lib/mount_darwin.c#L499
https://github.com/osxfuse/fuse/blob/c6a59bed40bb526c113f861ed49a78b5f224805a/lib/mount_darwin.c#L317

**Comment by llucps** [comment]
Thank you @midchildan  That's good news I hope! :)

**Comment by xsxnet** [comment]
@hanwen This commit solved my problem. Would you consider tagging a new semantic version for it ?

**Comment by hanwen** [comment]
i tagged v2.1.0. HTH.
