### ISSUE TITLE
Feature request: Server.Stop in order to allow resuming in a new process

### ISSUE THREAD

**Issue by MagicalTux** [hanwen/go-fuse#522]
It would be nice to have a function in the fuse server to "stop" serving requests and retrieve the underlying file descriptor so it can be for example passed to a new process (let's say, a new version of the running daemon) and operations resumed.

I guess this would look as follow:

* Stop reading for new operations
* Wait for all pending operations to finish executing
* Optionally invalidate all kernel cache (maybe as an option as some filesystems will likely keep the same inode numbers and data even after a restart)
* Stop the loop and return the underlying file descriptor (or a copy of it)

Maybe some more information will be required to make resuming work nicely (such as passing the initial flags received from the kernel?), in which case it should be also returned by the Stop method to be passed to a resume method.

**Comment by rfjakob** [comment]
Can't you mount the new fs on top of the running mountpoint?

**Comment by hanwen** [comment]
I can currently not spend time on go-fuse due to family obligations. Also, I understand your request, but I think it will be tricky to make work with the existing code, and either hard to use (because inodes are not persisted) or not better than remounting (because you have to flush *all* cached data). So, it is not very compelling as a feature request.

If you want to experiment with this, try to hack the `singleReader` code path.
