### ISSUE TITLE
Fails xfstests generic/257, panic: underflow: handle 170, count 6, object -1

### ISSUE THREAD

**Issue by rfjakob** [hanwen/go-fuse#57]
Running xfstests generic/257 against loopbackfs causes the following panic:

	panic: underflow: handle 170, count 6, object -1

	goroutine 6 [running]:
	log.Panicf(0x5ac270, 0x29, 0xc20802bdd0, 0x3, 0x3)
		/usr/lib/golang/src/log/log.go:314 +0xd0
	github.com/hanwen/go-fuse/fuse/nodefs.(*portableHandleMap).Forget(0xc208058060, 0xaa, 0x6, 0x0, 0xc208038a10)
		/home/jakob/src/github.com/hanwen/go-fuse/fuse/nodefs/handle.go:118 +0x23e
	github.com/hanwen/go-fuse/fuse/nodefs.(*FileSystemConnector).forgetUpdate(0xc20800a600, 0xaa, 0x6)
		/home/jakob/src/github.com/hanwen/go-fuse/fuse/nodefs/fsconnector.go:125 +0x9b
	github.com/hanwen/go-fuse/fuse/nodefs.(*rawBridge).Forget(0xc20800a600, 0xaa, 0x6)
		/home/jakob/src/github.com/hanwen/go-fuse/fuse/nodefs/fsops.go:108 +0x3c
    [....]

The test ( https://github.com/rfjakob/fuse-xfstests/blob/gocryptfs/tests/generic/257 ) runs "t_dir_offset2" ( https://github.com/rfjakob/fuse-xfstests/blob/gocryptfs/src/t_dir_offset2.c ) that exercises `getdents` and `lseek` on directories.

**Comment by hanwen** [comment]
whoops, that sounds very serious.

**Comment by hanwen** [comment]
can you show the entire stack trace? How reproducible is this? What if you compile loopback with the race detector?

**Comment by hanwen** [comment]
can you see if the problem goes away if you disable readdirplus,

        server.kernelSettings.Flags = input.Flags & (CAP_ASYNC_READ | CAP_BIG_WRITES | CAP_FILE_OPS |
                CAP_AUTO_INVAL_DATA | CAP_READDIRPLUS)

remove CAP_READDIRPLUS from this opcode.go

I suspect the following happens: readdir folds lookup and readdir into one roundtrip. If you mix this with seeking on directories, it's not obvious when to set the lookup count of inodes, because the FUSE process does the entire readdir up front, but the kernel only notices when it consumes the readdir output.

(I wouldn't be surprised if this were in part a kernel bug, btw.)

**Comment by rfjakob** [comment]
I can trigger this every time I run generic/257. Will check your
suggestions tonight and post the full stack trace.

**Comment by rfjakob** [comment]
Full backtrace: https://gist.github.com/rfjakob/686d05f9fb9681e724c5

Removing CAP_READDIRPLUS fixes the issue, the test passes!
